<?php
/**
 * Admin UI management.
 *
 * Registers the admin menu, settings, and handles form actions
 * (test email, clear log, disconnect OAuth).
 *
 * @package DIH_Google_SMTP
 */

defined( 'ABSPATH' ) || exit;

class DIH_SMTP_Admin {

	public static function register(): void {
		add_action( 'admin_menu',    [ __CLASS__, 'register_menu' ] );
		add_action( 'admin_init',    [ __CLASS__, 'register_settings' ] );
		add_action( 'admin_enqueue_scripts', [ __CLASS__, 'enqueue_assets' ] );
		add_action( 'admin_init',    [ __CLASS__, 'add_privacy_policy_content' ] );

		// Form action handlers
		add_action( 'admin_post_dih_smtp_send_test',       [ __CLASS__, 'handle_test_email' ] );
		add_action( 'admin_post_dih_smtp_clear_log',       [ __CLASS__, 'handle_clear_log' ] );
		add_action( 'admin_post_dih_smtp_disconnect_oauth',[ __CLASS__, 'handle_disconnect_oauth' ] );
	}

	// ── Menu ──────────────────────────────────────────────────────────────────

	public static function register_menu(): void {
		add_menu_page(
			__( 'DIH SMTP for Google Workspace', 'dih-google-smtp' ),
			__( 'GWS SMTP', 'dih-google-smtp' ),
			'manage_options',
			'dih-google-smtp',
			[ __CLASS__, 'render_page' ],
			'dashicons-email-alt',
			75
		);
	}

	// ── Settings ──────────────────────────────────────────────────────────────

	public static function register_settings(): void {
		register_setting(
			'dih_smtp_settings_group',
			DIH_SMTP_OPTION_KEY,
			[ 'sanitize_callback' => [ 'DIH_SMTP_Settings', 'sanitize' ] ]
		);
	}

	// ── Privacy ───────────────────────────────────────────────────────────────

	/**
	 * Suggest privacy policy text under Settings → Privacy → Policy Guide,
	 * because the debug log stores email addresses.
	 */
	public static function add_privacy_policy_content(): void {
		if ( ! function_exists( 'wp_add_privacy_policy_content' ) ) {
			return;
		}

		$content = __( 'This site sends email through Google Workspace SMTP servers. When debug logging is enabled, the SMTP conversation is stored in the site database; it can include sender and recipient email addresses, but not message content. The most recent 100 entries are kept until an administrator clears the log or the plugin is deleted.', 'dih-google-smtp' );

		wp_add_privacy_policy_content(
			__( 'DIH SMTP for Google Workspace', 'dih-google-smtp' ),
			wp_kses_post( wpautop( $content, false ) )
		);
	}

	// ── Assets ────────────────────────────────────────────────────────────────

	public static function enqueue_assets( string $hook ): void {
		if ( strpos( $hook, 'dih-google-smtp' ) === false ) {
			return;
		}
		wp_enqueue_style(
			'dih-smtp-admin',
			DIH_SMTP_URL . 'assets/admin.css',
			[],
			DIH_SMTP_VERSION
		);
		wp_enqueue_script(
			'dih-smtp-admin',
			DIH_SMTP_URL . 'assets/admin.js',
			[ 'wp-i18n' ], // Provides wp.i18n.__() for translatable JS strings
			DIH_SMTP_VERSION,
			true
		);
		// Load this plugin's JS translations (generated by WordPress.org language packs)
		wp_set_script_translations( 'dih-smtp-admin', 'dih-google-smtp' );
	}

	// ── Page Renderer ─────────────────────────────────────────────────────────

	public static function render_page(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$s = DIH_SMTP_Settings::get();

		$notices = [
			'oauth_success'      => [ 'success', __( '✅ Google account connected successfully!', 'dih-google-smtp' ) ],
			'oauth_error'        => [ 'error',   __( '❌ OAuth2 connection failed. Check your Client ID/Secret and try again.', 'dih-google-smtp' ) ],
			'oauth_disconnected' => [ 'warning', __( '⚠️ OAuth2 disconnected.', 'dih-google-smtp' ) ],
			'test_success'       => [ 'success', __( '✅ Test email sent successfully!', 'dih-google-smtp' ) ],
			'test_fail'          => [ 'error',   __( '❌ Test email failed. Check your settings and debug log.', 'dih-google-smtp' ) ],
			'test_invalid'       => [ 'error',   __( '❌ Please enter a valid email address.', 'dih-google-smtp' ) ],
			'log_cleared'        => [ 'success', __( '✅ Debug log cleared.', 'dih-google-smtp' ) ],
		];

		$tabs = [
			'settings' => __( 'Settings', 'dih-google-smtp' ),
			'oauth'    => __( 'OAuth2 Setup', 'dih-google-smtp' ),
			'test'     => __( 'Test Email', 'dih-google-smtp' ),
			'debug'    => __( 'Debug Log', 'dih-google-smtp' ),
			'help'     => __( 'Help', 'dih-google-smtp' ),
		];

		// Read-only GET params that only choose what to display — no state change,
		// so no nonce is needed. Both are validated against an allowlist below.
		// phpcs:disable WordPress.Security.NonceVerification.Recommended
		$tab    = sanitize_key( wp_unslash( $_GET['tab'] ?? 'settings' ) );
		$notice = sanitize_key( wp_unslash( $_GET['dih_smtp_notice'] ?? '' ) );
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		if ( ! isset( $tabs[ $tab ] ) ) {
			$tab = 'settings';
		}
		?>
		<div class="wrap dih-smtp-wrap">
			<h1>
				<span class="dashicons dashicons-email-alt" style="font-size:28px;color:#4285F4;vertical-align:middle;"></span>
				<?php esc_html_e( 'DIH SMTP for Google Workspace', 'dih-google-smtp' ); ?>
				<span class="dih-smtp-version">v<?php echo esc_html( DIH_SMTP_VERSION ); ?></span>
			</h1>

			<?php if ( $notice && isset( $notices[ $notice ] ) ) :
				[ $type, $msg ] = $notices[ $notice ]; ?>
				<div class="notice notice-<?php echo esc_attr( $type ); ?> is-dismissible">
					<p><?php echo esc_html( $msg ); ?></p>
				</div>
			<?php endif; ?>

			<nav class="nav-tab-wrapper">
				<?php foreach ( $tabs as $key => $label ) : ?>
					<a href="<?php echo esc_url( admin_url( "admin.php?page=dih-google-smtp&tab={$key}" ) ); ?>"
					   class="nav-tab <?php echo $tab === $key ? 'nav-tab-active' : ''; ?>">
						<?php echo esc_html( $label ); ?>
					</a>
				<?php endforeach; ?>
			</nav>

			<?php include DIH_SMTP_DIR . "admin/views/tab-{$tab}.php"; // $tab is allowlisted above ?>
		</div>
		<?php
	}

	// ── Action Handlers ───────────────────────────────────────────────────────

	public static function handle_test_email(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'dih-google-smtp' ) );
		}
		check_admin_referer( 'dih_smtp_test_email' );

		// PHP/WordPress add slashes to $_POST — unslash first, then sanitize
		$to = isset( $_POST['test_email_to'] )
			? sanitize_email( wp_unslash( $_POST['test_email_to'] ) )
			: get_option( 'admin_email' );

		// sanitize_email() returns '' for garbage — validate before sending
		if ( ! is_email( $to ) ) {
			wp_safe_redirect( admin_url( 'admin.php?page=dih-google-smtp&tab=test&dih_smtp_notice=test_invalid' ) );
			exit;
		}

		$subject = sprintf(
			/* translators: %s: date and time the test email was sent. */
			__( 'DIH SMTP Test — %s', 'dih-google-smtp' ),
			current_time( 'Y-m-d H:i:s' )
		);

		// One translatable string per line — translators shouldn't have to handle "\n"
		$message = implode(
			"\n",
			[
				__( 'Test email from WordPress via Google Workspace SMTP.', 'dih-google-smtp' ),
				'',
				/* translators: %s: plugin name. */
				sprintf( __( 'Plugin: %s', 'dih-google-smtp' ), 'DIH SMTP for Google Workspace' ),
				/* translators: %s: site URL. */
				sprintf( __( 'Site: %s', 'dih-google-smtp' ), get_bloginfo( 'url' ) ),
			]
		);

		// Don't write the recipient address to the log — it's personal data
		DIH_SMTP_Logger::log( 'Sending test email.' );

		$result = wp_mail( $to, $subject, $message );
		$notice = $result ? 'test_success' : 'test_fail';

		wp_safe_redirect( admin_url( "admin.php?page=dih-google-smtp&tab=test&dih_smtp_notice={$notice}" ) );
		exit;
	}

	public static function handle_clear_log(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'dih-google-smtp' ) );
		}
		check_admin_referer( 'dih_smtp_clear_log' );
		DIH_SMTP_Logger::clear();
		wp_safe_redirect( admin_url( 'admin.php?page=dih-google-smtp&tab=debug&dih_smtp_notice=log_cleared' ) );
		exit;
	}

	public static function handle_disconnect_oauth(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'dih-google-smtp' ) );
		}
		check_admin_referer( 'dih_smtp_disconnect_oauth' );
		DIH_SMTP_OAuth::disconnect( ! empty( $_POST['revoke'] ) );
		wp_safe_redirect( admin_url( 'admin.php?page=dih-google-smtp&tab=oauth&dih_smtp_notice=oauth_disconnected' ) );
		exit;
	}
}
